Try removing the iOS scemes

diff --git a/Scripts/bootstrap b/Scripts/bootstrap
--- a/Scripts/bootstrap
+++ b/Scripts/bootstrap
@@ -5,14 +5,23 @@ brew update
 brew install carthage --HEAD
 
 echo "*********** Installing dependencies with Carthage ***********"
-carthage bootstrap
+carthage bootstrap --no-build
 ret=$?
 if [ $ret -ne 0 ]; then 
-	echo "⚠ Carthage command failed, here are the logs (maybe)"
+	echo "⚠ Carthage bootstrap command failed, here are the logs (maybe)"
 	find $TMPDIR -type f -name "carthage-xcodebuild.*" -exec cat {} \;
 	exit $ret
 fi
 
+find Carthage/Checkouts -type -f -name "*iOS.xcscheme" -delete
+
+carthage build
+ret=$?
+if [ $ret -ne 0 ]; then 
+	echo "⚠ Carthage build command failed, here are the logs (maybe)"
+	find $TMPDIR -type f -name "carthage-xcodebuild.*" -exec cat {} \;
+	exit $ret
+fi
 echo "*********** Installing ruby dependencies ***********"
 gem install bundler --no-rdoc --no-ri
 bundle install
